name: run amy 1
on:
  workflow_dispatch:    # 保留手动触发能力
#  schedule:
#    - cron: '0 */6 * * *'  # 每6小时运行一次[5,7](@ref)

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 设置最长运行6小时[6](@ref)
    steps:
    - name: Download and setup amy4Server
      run: |
        wget -O amy4Server.zip https://raw.githubusercontent.com/mmxdxmm/amy4Server/refs/heads/main/amy4Server_amd64.zip
        unzip amy4Server.zip
        sudo mkdir -p /usr/local/amy4Server/
        sudo cp -r ./amy4Server/* /usr/local/amy4Server/
        cd /usr/local/amy4Server/
        sudo chmod 777 ./*
        sudo wget https://chmlfrp.cn/dw/ChmlFrp-0.51.2_240715_linux_amd64.tar.gz -O ChmlFrp-0.51.2_240715_linux_amd64.tar.gz
        sudo tar -xvf ChmlFrp-0.51.2_240715_linux_amd64.tar.gz
        sudo chmod 777 ./ChmlFrp-0.51.2_240715_linux_amd64/*

    - name: Start services
      run: |
        cd /usr/local/amy4Server/
        ./amy4Server -config ./amy4Server.json & sudo ./ChmlFrp-0.51.2_240715_linux_amd64/frpc -u "${{ secrets.FRP_USER }}" -p 116058
        
